spring.application.name=ForoHub

spring.datasource.url=jdbc:mysql://localhost/forohub
spring.datasource.driver-clas-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=root1234

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.error.include-stacktrace=never

api.security.token.secret=${JWT_SECRET:12345678}
logging.level.org.springframework.security=DEBUG